#' Take list of count dataframes and turn it into a single dataframe
#'
#' This function merges the counts dfs generated by calcPSI_bulk
#'@param counts_list Path to the info file which contains (at least) the following columns: id, compilation (sra_human, sra_mouse, tcga, gtex, encode), strand, novel_junc_left_coord, novel_junc_right_coord, canon_junc_coord.
#'@param wide T/F value - whether dataframe should have one column per novel junction or be a long df compatible with packages such as ggplot2
#'@returns Single dataframe
#'@export
#'@references
#' Christopher Wilks, Phani Gaddipati, Abhinav Nellore, Ben Langmead.
#' Snaptron: querying splicing patterns across tens of thousands of RNA-seq samples.
#' Bioinformatics 34, 114-116 (2018). https://doi.org/10.1093/bioinformatics/btx547
#'
#' Sinha, I.R., Sandal, P.S., Spence, H. et al.
#' Large-scale RNA-Seq mining reveals ciclopirox olamine induces TDP-43 cryptic exons.
#' Nat Commun 16, 6878 (2025). https://doi.org/10.1038/s41467-025-62004-5

flattenCounts <- function(counts_list, wide = T,  ){
  counts_list_long <- list_rbind(counts_list) %>% as.data.frame()

  if(wide = T){
    counts_list_wide <- counts_list_long %>% dplyr::select(-c(psi_r, psi_l)) %>%
      pivot_wider(id_cols = 1, names_from = novel_junc_id, values_from = avgPSI)

    return(counts_list_wide)
  } else{
    return(counts_list_long)
  }
}